/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sgef.telas;

import br.com.sgef.dal.ModuloConexao;
import br.com.sgef.dao.FornecedorDAO;
import br.com.sgef.model.Fornecedor;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author BrunoRomeroAlencar
 */
public class TelaCadFornecedor extends javax.swing.JInternalFrame {
    
    private static TelaCadFornecedor telacadFornecedor;

    public static TelaCadFornecedor getInsancia() {
        if (telacadFornecedor == null) {
            telacadFornecedor = new TelaCadFornecedor();

        }
        return telacadFornecedor;

    }

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaCadFornecedor
     */
    public TelaCadFornecedor() {
        initComponents();
        conexao = ModuloConexao.conector();
        
        tblFornecedor.getColumnModel().getColumn(0).setMaxWidth(40);

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CodFornecedor = new javax.swing.JTextField();
        DescFornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EndFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TelefoneFornecedor = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFornecedor = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CidadeFornecedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboUfFornecedor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        BairroFornecedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NumFornecedor = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Fornecedor");
        setToolTipText("");

        jLabel1.setText("Cód.");

        jLabel2.setText("Fornecedor*");

        CodFornecedor.setEnabled(false);

        jLabel3.setText("Endereço*");

        jLabel4.setText("Telefone*");

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/delete.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/clean.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/alter.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/saved.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tblFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód", "Fornecedor", "Cidade", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFornecedor);

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Método de Pesquisa");

        jLabel5.setText("Cidade*");

        jLabel6.setText("UF");

        ComboUfFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel7.setText("Bairro*");

        jLabel9.setText("Nº  *");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(6, 6, 6)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(EndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BairroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(NumFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DescFornecedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboUfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboUfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BairroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NumFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(btnExcluir)
                    .addComponent(jButton3)
                    .addComponent(btnSave))
                .addGap(4, 4, 4)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Seleciona o registro na tabela e ao clicar aqui exclui o fornecedor
        // Se nenhum registro tiver selecionado o sistema avisa o usuario
        
        Fornecedor fornecedor = new Fornecedor();
        FornecedorDAO dao = new FornecedorDAO();
        
        
        if (CodFornecedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um registro para ser Excluido!");
        }else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            dialogButton = JOptionPane.showConfirmDialog (null, "Deseja Realmente Excluir o Fornecedor?",
                    "ATENÇÃO", dialogButton);
            if (dialogButton == JOptionPane.YES_OPTION) {
                fornecedor.setId(Integer.parseInt(CodFornecedor.getText()));
                dao.excluir(fornecedor);
                //limpar campos
                CodFornecedor.setText(null);
                DescFornecedor.setText(null);
                CidadeFornecedor.setText(null);
                ComboUfFornecedor.setSelectedIndex(1);
                TelefoneFornecedor.setText(null);
                EndFornecedor.setText(null);
                BairroFornecedor.setText(null);
                NumFornecedor.setText(null);
                btnSave.setEnabled(true);

            }
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedor.getModel();
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblFornecedor.getModel()).setRowCount(0);
        
        for (Iterator<Fornecedor> it = dao.read(this.txtPesquisar.getText()).iterator(); it.hasNext();) {
            Fornecedor forn = it.next();
            modelo.addRow(new Object[]{
                forn.getId(),
                forn.getFornecedor(),
                forn.getCidade(),
                forn.getTelefone()                   
            });
        }
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Limpar campos ao clicar no botao clean
        
        CodFornecedor.setText(null);
        DescFornecedor.setText(null);
        CidadeFornecedor.setText(null);
        ComboUfFornecedor.setSelectedIndex(1);
        TelefoneFornecedor.setText(null);
        EndFornecedor.setText(null);
        BairroFornecedor.setText(null);
        NumFornecedor.setText(null);
        btnSave.setEnabled(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Método Para alterar Fornecedor
        FornecedorDAO dao = new FornecedorDAO();
        Fornecedor f = new Fornecedor();
        
        if(CodFornecedor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um registro para ser editado !");
        }
        else if ((DescFornecedor.getText().isEmpty()) || (CidadeFornecedor.getText().isEmpty()) ||
                (TelefoneFornecedor.getText().isEmpty())|| (EndFornecedor.getText().isEmpty())|| 
                (BairroFornecedor.getText().isEmpty()) || (NumFornecedor.getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "Preencha Todos os Campos Obrigatórios (*)");   
        }else{
            f.setId(Integer.parseInt(CodFornecedor.getText()));
            f.setFornecedor(DescFornecedor.getText());
            f.setCidade(CidadeFornecedor.getText());
            f.setUf(ComboUfFornecedor.getSelectedItem().toString());
            f.setTelefone(TelefoneFornecedor.getText());
            f.setEndereco(EndFornecedor.getText());
            f.setBairro(BairroFornecedor.getText());
            f.setNumero(NumFornecedor.getText());
            
            dao.alterar(f);
            
            CodFornecedor.setText(null);
            DescFornecedor.setText(null);
            CidadeFornecedor.setText(null);
            ComboUfFornecedor.setSelectedIndex(1);
            TelefoneFornecedor.setText(null);
            EndFornecedor.setText(null);
            BairroFornecedor.setText(null);
            NumFornecedor.setText(null);
            
            btnSave.setEnabled(true);

        }
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedor.getModel();
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblFornecedor.getModel()).setRowCount(0);
        
        for (Iterator<Fornecedor> it = dao.read(this.txtPesquisar.getText()).iterator(); it.hasNext();) {
            Fornecedor forn = it.next();
            modelo.addRow(new Object[]{
                forn.getId(),
                forn.getFornecedor(),
                forn.getCidade(),
                forn.getTelefone()                   
            });
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Botao salvar - ao clicar valida os campos e se estiver tudo ok salva no DB
       
        Fornecedor forn = new Fornecedor();
        FornecedorDAO dao = new FornecedorDAO();
        
        if ((DescFornecedor.getText().isEmpty()) || (CidadeFornecedor.getText().isEmpty()) || 
            (TelefoneFornecedor.getText().isEmpty()) || (EndFornecedor.getText().isEmpty()) ||
            (BairroFornecedor.getText().isEmpty()) || (NumFornecedor.getText().isEmpty())) {
               
            JOptionPane.showMessageDialog(null, "Preencha Todos os Campos Obrigatórios (*)");
                
        }else{
        
            forn.setFornecedor(DescFornecedor.getText());
            forn.setCidade(CidadeFornecedor.getText());
            forn.setUf(ComboUfFornecedor.getSelectedItem().toString());
            forn.setTelefone(TelefoneFornecedor.getText());
            forn.setEndereco(EndFornecedor.getText());
            forn.setBairro(BairroFornecedor.getText());
            forn.setNumero(NumFornecedor.getText());

            dao.adicionar(forn);
            
            CodFornecedor.setText(null);
            DescFornecedor.setText(null);
            CidadeFornecedor.setText(null);
            ComboUfFornecedor.setSelectedIndex(1);
            TelefoneFornecedor.setText(null);
            EndFornecedor.setText(null);
            BairroFornecedor.setText(null);
            NumFornecedor.setText(null);
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedor.getModel();
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblFornecedor.getModel()).setRowCount(0);
        
        for (Iterator<Fornecedor> it = dao.read(this.txtPesquisar.getText()).iterator(); it.hasNext();) {
            Fornecedor fornecedor = it.next();
            modelo.addRow(new Object[]{
                fornecedor.getId(),
                fornecedor.getFornecedor(),
                fornecedor.getCidade(),
                fornecedor.getTelefone()                   
            });
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        //ao digitar no campo de pesquisa ou apertar enter faz a consulta no banco utilizando like

        FornecedorDAO fdao = new FornecedorDAO();
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedor.getModel();
        
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblFornecedor.getModel()).setRowCount(0);
        
        for (Fornecedor f: fdao.read(this.txtPesquisar.getText().toString())) {
            modelo.addRow(new Object[]{
                f.getId(),
                f.getFornecedor(),
                f.getCidade(),
                f.getTelefone()
                   
            });

        }
    
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tblFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedorMouseClicked
       /*Pega o id do campo codigo e faz a consulta no banco de dados,
        após fazer a consulta, pega os atributos do fornecedor e seta para os campos 
        do formulario conforme clica sobre o registro da tabela na tela*/
        FornecedorDAO fdao = new FornecedorDAO();
        Fornecedor fornecedor = new Fornecedor();

        int k = tblFornecedor.getSelectedRow();
        Object id = tblFornecedor.getValueAt(k, 0);
        CodFornecedor.setText(id.toString());
        fornecedor.setId(Integer.parseInt(id.toString()));

        //setar o restante dos campos
        int setar = tblFornecedor.getSelectedRow();
        DescFornecedor.setText(fdao.pesquisa_por_id((Integer) id).getFornecedor());
        CidadeFornecedor.setText(fdao.pesquisa_por_id((Integer) id).getCidade());
        ComboUfFornecedor.setSelectedItem(fdao.pesquisa_por_id((Integer) id).getUf());
        TelefoneFornecedor.setText(fdao.pesquisa_por_id((Integer) id).getTelefone());
        EndFornecedor.setText(fdao.pesquisa_por_id((Integer) id).getEndereco());
        BairroFornecedor.setText(fdao.pesquisa_por_id((Integer) id).getBairro());
        NumFornecedor.setText(fdao.pesquisa_por_id((Integer) id).getNumero());
        //botao salvar inativo
        btnSave.setEnabled(false);
           
    }//GEN-LAST:event_tblFornecedorMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // ao clicar no botao buscar faz a consulta com o parametro passar no txtPesquisar
        
        FornecedorDAO fdao = new FornecedorDAO();
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedor.getModel();
        
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblFornecedor.getModel()).setRowCount(0);
        
        for (Fornecedor f: fdao.read(this.txtPesquisar.getText().toString())) {
            modelo.addRow(new Object[]{
                f.getId(),
                f.getFornecedor(),
                f.getCidade(),
                f.getTelefone()
                   
            });

        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroFornecedor;
    private javax.swing.JTextField CidadeFornecedor;
    private javax.swing.JTextField CodFornecedor;
    private javax.swing.JComboBox ComboUfFornecedor;
    private javax.swing.JTextField DescFornecedor;
    public javax.swing.JTextField EndFornecedor;
    private javax.swing.JTextField NumFornecedor;
    private javax.swing.JTextField TelefoneFornecedor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable tblFornecedor;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
