/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sgef.telas;

import java.sql.*;
import br.com.sgef.dal.ModuloConexao;
import br.com.sgef.dao.UserDAO;
import br.com.sgef.model.User;
import java.awt.Dimension;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author BrunoRomeroAlencar
 */
public class TelaCadUser extends javax.swing.JInternalFrame{

    private static TelaCadUser telacadUser;

    public static TelaCadUser getInsancia() {
        if (telacadUser == null) {
            telacadUser = new TelaCadUser();

        }
        return telacadUser;

    }

    

    /**
     * Creates new form TelaCadUser
     */
    public TelaCadUser() {
        initComponents();
        comboboxPerfilUser.setSelectedItem(1);
        
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codUser = new javax.swing.JTextField();
        nameUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginUser = new javax.swing.JTextField();
        pwdUser = new javax.swing.JTextField();
        comboboxPerfilUser = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Usuários");
        setToolTipText("");

        jLabel1.setText("Código");

        jLabel2.setText("Nome*");

        codUser.setEnabled(false);

        nameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUserActionPerformed(evt);
            }
        });

        jLabel3.setText("Login*");

        jLabel4.setText("Senha*");

        comboboxPerfilUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Usuario", "Motorista" }));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/saved.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaveKeyPressed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/alter.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/clean.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jLabel5.setText("Perfil*");

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód", "Nome", "Login", "Senha", "Perfil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Método de Pesquisa");

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/delete.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Buscar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(codUser, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nameUser)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(pwdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(comboboxPerfilUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboboxPerfilUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton2)
                        .addComponent(jToggleButton1)))
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 529, 412);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        UserDAO user = new UserDAO();
        User u = new User();// criei um objeto user 
        //marcar para o combo box ja vim marcado alguma opção
        if ((nameUser.getText().isEmpty()) || (loginUser.getText().isEmpty()) || (pwdUser.getText().isEmpty()) || (comboboxPerfilUser.getSelectedItem().toString().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha Todos os Campos Obrigatórios (*)");
                
        }else{
        
            u.setNome(nameUser.getText());
            u.setUsuario(loginUser.getText());
            u.setSenha(pwdUser.getText());
            u.setperfilUser(comboboxPerfilUser.getSelectedItem().toString());

            user.adicionar(u);
            
            codUser.setText(null);
            nameUser.setText(null);
            loginUser.setText(null);
            pwdUser.setText(null);
            
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblUser.getModel();
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblUser.getModel()).setRowCount(0);
        
        for (Iterator<User> it = user.read(this.txtPesquisar.getText()).iterator(); it.hasNext();) {
            User user1 = it.next();
            modelo.addRow(new Object[]{
                user1.getId(),
                user1.getNome(),
                user1.getUsuario(),
                user1.getSenha(),
                user1.getperilUser()
                   
            });
        }
 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        
        UserDAO user = new UserDAO();
        DefaultTableModel modelo = (DefaultTableModel) tblUser.getModel();
        
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblUser.getModel()).setRowCount(0);
        
        for (User u: user.read(this.txtPesquisar.getText().toString())) {
            modelo.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getUsuario(),
                u.getSenha(),
                u.getperilUser()
                   
            });
   
        }
        
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
       // setar_campos();
        User u = new User();
        UserDAO user = new UserDAO();
        
        int k = tblUser.getSelectedRow();
        String id = (String) tblUser.getValueAt(k, 0).toString();
        String nome = (String) tblUser.getValueAt(k, 1);
        String usuario = (String) tblUser.getValueAt(k, 2);
        String senha = (String) tblUser.getValueAt(k, 3);
        String perfil = (String) tblUser.getValueAt(k, 4);
        
        codUser.setText(id);
        nameUser.setText(nome); 
        loginUser.setText(usuario); 
        pwdUser.setText(senha); 
        comboboxPerfilUser.setSelectedItem(perfil);
        btnSave.setEnabled(false);
 
    }//GEN-LAST:event_tblUserMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Método para alterar
      
        
        UserDAO user = new UserDAO();
        User u = new User();
        
        if(codUser.getText().toString().isEmpty()){
               JOptionPane.showMessageDialog(null, "Selecione um registro para ser editado !");
        }
        else if ((nameUser.getText().isEmpty()) || (loginUser.getText().isEmpty()) || (pwdUser.getText().isEmpty()) || (comboboxPerfilUser.getSelectedItem().toString().isEmpty())) {
           JOptionPane.showMessageDialog(null, "Preencha Todos os Campos Obrigatórios (*)");
        }  
        else{

            u.setId(Integer.parseInt(codUser.getText()));
            u.setNome(nameUser.getText());
            u.setUsuario(loginUser.getText());
            u.setSenha(pwdUser.getText());
            u.setperfilUser(comboboxPerfilUser.getSelectedItem().toString());

            user.alterar(u);
            
            codUser.setText(null);
            nameUser.setText(null);
            loginUser.setText(null);
            pwdUser.setText(null);
            btnSave.setEnabled(true);
            
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblUser.getModel();
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblUser.getModel()).setRowCount(0);
        
        for (Iterator<User> it = user.read(this.txtPesquisar.getText()).iterator(); it.hasNext();) {
            User user1 = it.next();
            modelo.addRow(new Object[]{
                user1.getId(),
                user1.getNome(),
                user1.getUsuario(),
                user1.getSenha(),
                user1.getperilUser()
                   
            });
        }
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyPressed

    private void btnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Limpar campos ao clicar no botao clean
        codUser.setText(null);
        nameUser.setText(null);
        loginUser.setText(null);
        pwdUser.setText(null);

        btnSave.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        //limpar();
    }//GEN-LAST:event_jButton2KeyPressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        //Excluir usuario por id
        UserDAO user = new UserDAO();
        User u = new User();
        
        
        if(codUser.getText().toString().isEmpty()){
               JOptionPane.showMessageDialog(null, "Selecione um registro para ser Excluido!");
        }else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            dialogButton = JOptionPane.showConfirmDialog (null, "Deseja Realmente Excluir Usuário?","ATENÇÃO", dialogButton);
            if (dialogButton == JOptionPane.YES_OPTION) {

                u.setId(Integer.parseInt(codUser.getText()));
                user.excluir(u);

                //Limpar campos
                codUser.setText(null);
                nameUser.setText(null);
                loginUser.setText(null);
                pwdUser.setText(null);
                comboboxPerfilUser.setSelectedIndex(0);
                //ativa botao salvar
                btnSave.setEnabled(true);    
            }
        }
        DefaultTableModel modelo = (DefaultTableModel) tblUser.getModel();
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblUser.getModel()).setRowCount(0);
        
        for (Iterator<User> it = user.read(this.txtPesquisar.getText()).iterator(); it.hasNext();) {
            User user1 = it.next();
            modelo.addRow(new Object[]{
                user1.getId(),
                user1.getNome(),
                user1.getUsuario(),
                user1.getSenha(),
                user1.getperilUser()
                   
            });
        }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void nameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameUserActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // Popular Tabela 

        UserDAO user = new UserDAO();
        DefaultTableModel modelo = (DefaultTableModel) tblUser.getModel();
        
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblUser.getModel()).setRowCount(0);
        
        for (User u: user.read(this.txtPesquisar.getText().toString())) {
            modelo.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getUsuario(),
                u.getSenha(),
                u.getperilUser()
                   
            });

        }
  
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    public javax.swing.JTextField codUser;
    public javax.swing.JComboBox comboboxPerfilUser;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    public javax.swing.JTextField loginUser;
    public javax.swing.JTextField nameUser;
    public javax.swing.JTextField pwdUser;
    public javax.swing.JTable tblUser;
    public javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
