/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sgef.telas;

import br.com.sgef.dao.ClienteDAO;
import br.com.sgef.model.Cliente;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bruno
 */
public class TelaCadCli extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadCli
     */
    public TelaCadCli() {
        initComponents();
        tblCliente.getColumnModel().getColumn(0).setMaxWidth(40);
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CodCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NomeCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CidadeCli = new javax.swing.JTextField();
        ComboUf = new javax.swing.JComboBox();
        TelCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EnderecoCli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BairroCli = new javax.swing.JTextField();
        NumCli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Cliente");
        setToolTipText("");
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(658, 410));

        jLabel2.setText("Código");

        CodCli.setEditable(false);
        CodCli.setEnabled(false);
        CodCli.setFocusable(false);

        jLabel3.setText("Nome*");

        jLabel4.setText("Cidade*");

        ComboUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel5.setText("Telefone*");

        jLabel6.setText("UF");

        jLabel7.setText("Endereço*");

        jLabel8.setText("Bairro*");

        jLabel9.setText("N*");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/saved.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/delete.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/clean.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sgef/icones/alter.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Método de Pesquisa");

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód", "Cliente", "Cidade", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(ComboUf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TelCli)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodCli, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(NomeCli))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnderecoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(NumCli))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnderecoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2)
                        .addComponent(btnExcluir)
                        .addComponent(jButton3)
                        .addComponent(btnSave))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 664, 443);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Botao salvar - ao clicar valida os campos e se estiver tudo ok salva no DB
        
        Cliente cliente = new Cliente();
        ClienteDAO cdao = new ClienteDAO();
        
        if ((NomeCli.getText().isEmpty()) || (CidadeCli.getText().isEmpty()) || 
            (TelCli.getText().isEmpty()) || (EnderecoCli.getText().isEmpty()) ||
            (BairroCli.getText().isEmpty()) || (NumCli.getText().isEmpty())) {
               
            JOptionPane.showMessageDialog(null, "Preencha Todos os Campos Obrigatórios (*)");
                
        }else{
        
            cliente.setNome(NomeCli.getText());
            cliente.setCidade(CidadeCli.getText());
            cliente.setUf(ComboUf.getSelectedItem().toString());
            cliente.setTelefone(TelCli.getText());
            cliente.setEndereco(EnderecoCli.getText());
            cliente.setBairro(BairroCli.getText());
            cliente.setNumero(NumCli.getText());

            cdao.adicionar(cliente);
            
            CodCli.setText(null);
            NomeCli.setText(null);
            CidadeCli.setText(null);
            ComboUf.setSelectedIndex(1);
            TelCli.setText(null);
            EnderecoCli.setText(null);
            BairroCli.setText(null);
            NumCli.setText(null);
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblCliente.getModel()).setRowCount(0);
        
        for (Cliente cli: cdao.read(this.txtPesquisar.getText().toString())) {
            modelo.addRow(new Object[]{
                cli.getId(),
                cli.getNome(),
                cli.getCidade(),
                cli.getTelefone()

            });

        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Seleciona o registro na tabela e ao clicar aqui exclui o fornecedor
        // Se nenhum registro tiver selecionado o sistema avisa o usuario
        
        Cliente cliente = new Cliente();
        ClienteDAO dao = new ClienteDAO();
        
        
        if (CodCli.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um registro para ser Excluido!");
        }else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            dialogButton = JOptionPane.showConfirmDialog (null, "Deseja Realmente Excluir o Cliente?",
                "ATENÇÃO", dialogButton);
            if (dialogButton == JOptionPane.YES_OPTION) {
                cliente.setId(Integer.parseInt(CodCli.getText()));
                dao.excluir(cliente);
                //limpar campos
                CodCli.setText(null);
                NomeCli.setText(null);
                CidadeCli.setText(null);
                ComboUf.setSelectedIndex(1);
                TelCli.setText(null);
                EnderecoCli.setText(null);
                BairroCli.setText(null);
                NumCli.setText(null);
                btnSave.setEnabled(true);
            
            }
            
        }
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblCliente.getModel()).setRowCount(0);
        
        for (Cliente cli: dao.read(this.txtPesquisar.getText().toString())) {
            modelo.addRow(new Object[]{
                cli.getId(),
                cli.getNome(),
                cli.getCidade(),
                cli.getTelefone()

            });

        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Limpar campos ao clicar no botao clean
        
        CodCli.setText(null);
        NomeCli.setText(null);
        CidadeCli.setText(null);
        ComboUf.setSelectedIndex(1);
        TelCli.setText(null);
        EnderecoCli.setText(null);
        BairroCli.setText(null);
        NumCli.setText(null);
        btnSave.setEnabled(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Método Para alterar Fornecedor
        
        ClienteDAO cdao = new ClienteDAO();
        Cliente c = new Cliente();
        
        if(CodCli.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione um registro para ser editado !");
        }
        else if ((NomeCli.getText().isEmpty()) || (CidadeCli.getText().isEmpty()) ||
                (TelCli.getText().isEmpty())|| (EnderecoCli.getText().isEmpty())|| 
                (BairroCli.getText().isEmpty()) || (NumCli.getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "Preencha Todos os Campos Obrigatórios (*)");   
        }else{
            c.setId(Integer.parseInt(CodCli.getText()));
            c.setNome(NomeCli.getText());
            c.setCidade(CidadeCli.getText());
            c.setUf(ComboUf.getSelectedItem().toString());
            c.setTelefone(TelCli.getText());
            c.setEndereco(EnderecoCli.getText());
            c.setBairro(BairroCli.getText());
            c.setNumero(NumCli.getText());
            
            cdao.alterar(c);
            
            CodCli.setText(null);
            NomeCli.setText(null);
            CidadeCli.setText(null);
            ComboUf.setSelectedIndex(1);
            TelCli.setText(null);
            EnderecoCli.setText(null);
            BairroCli.setText(null);
            NumCli.setText(null);
            
            btnSave.setEnabled(true);

        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblCliente.getModel()).setRowCount(0);
        
        for (Cliente cli: cdao.read(this.txtPesquisar.getText().toString())) {
            modelo.addRow(new Object[]{
                cli.getId(),
                cli.getNome(),
                cli.getCidade(),
                cli.getTelefone()

            });

        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        //ao digitar no campo de pesquisa ou apertar enter faz a consulta no banco utilizando like
        
        ClienteDAO cdao = new ClienteDAO();
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblCliente.getModel()).setRowCount(0);
        
        for (Cliente c: cdao.read(this.txtPesquisar.getText().toString())) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCidade(),
                c.getTelefone()

            });

        }
        
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // ao clicar no botao buscar faz a consulta com o parametro passar no txtPesquisar
        
        ClienteDAO cdao = new ClienteDAO();
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        
        //a linha abaixo limpa a tabela antes de colocar o resultado da pesquisa
        ((DefaultTableModel) tblCliente.getModel()).setRowCount(0);
        
        for (Cliente c: cdao.read(this.txtPesquisar.getText().toString())) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCidade(),
                c.getTelefone()

            });

        }

        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        /*Pega o id do campo codigo e faz a consulta no banco de dados,
        após fazer a consulta, pega os atributos e seta para os campos
        do formulario conforme clica sobre o registro da tabela na tela*/
        
        ClienteDAO cdao = new ClienteDAO();
        Cliente cliente = new Cliente();

        int k = tblCliente.getSelectedRow();
        Object id = tblCliente.getValueAt(k, 0);
        CodCli.setText(id.toString());
        cliente.setId(Integer.parseInt(id.toString()));
        
        //setar o restante dos campos
        int setar = tblCliente.getSelectedRow();
        NomeCli.setText(cdao.pesquisa_por_id((Integer) id).getNome());
        CidadeCli.setText(cdao.pesquisa_por_id((Integer) id).getCidade());
        ComboUf.setSelectedItem(cdao.pesquisa_por_id((Integer) id).getUf());
        TelCli.setText(cdao.pesquisa_por_id((Integer) id).getTelefone());
        EnderecoCli.setText(cdao.pesquisa_por_id((Integer) id).getEndereco());
        BairroCli.setText(cdao.pesquisa_por_id((Integer) id).getBairro());
        NumCli.setText(cdao.pesquisa_por_id((Integer) id).getNumero());
        //botao salvar inativo
        btnSave.setEnabled(false);
        

    }//GEN-LAST:event_tblClienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroCli;
    private javax.swing.JTextField CidadeCli;
    private javax.swing.JTextField CodCli;
    private javax.swing.JComboBox ComboUf;
    private javax.swing.JTextField EnderecoCli;
    private javax.swing.JTextField NomeCli;
    private javax.swing.JTextField NumCli;
    private javax.swing.JTextField TelCli;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
